# -*- coding: utf-8 -*-
"""20th Feb TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hBlhBBDIYFS0iDgGM1kgHrLm0JT-3HaR
"""

#Numpy Speed test
import numpy as np
import time


numbers = list(range(1000000))
array = np.array(numbers)

# Test Python list speed
start = time.time()

result_list = []
for i in numbers:
    result_list.append(i * 2)

end = time.time()
print("Python List Time:", end - start)

# Test NumPy array speed
start = time.time()

result_array = array * 2

end = time.time()
print("NumPy Array Time:", end - start)

#NumPy array performs operations faster than Python lists for large datasets.
#Python lists take more time because operations are done using loops.
#NumPy is more efficient for numerical computations on large data.

