# -*- coding: utf-8 -*-
"""21st March TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pe3hGfQlytlpQ8FkCzo89WSfQJtovXQJ
"""

import string
stopwords = ["is", "the", "and", "i", "this", "so", "much"]
# Input text
text = "This is AMAZING!!! I love this movie so much"
print("Original Text:")
print(text)
# Step 1: lowercase conversion
text = text.lower()
# Step 2: remove punctuation
text = text.translate(str.maketrans('', '', string.punctuation))
# Step 3: split into words
words = text.split()
# Step 4: remove stopwords
clean_words = []
for word in words:
    if word not in stopwords:
        clean_words.append(word)

# Final cleaned text
clean_text = " ".join(clean_words)

print("\nCleaned Text:")
print(clean_text)

