# -*- coding: utf-8 -*-
"""22nd March TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LG050_HzbvjIjzT5Avowle1s6Jewtl99
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
data = {
    "Income":[15,16,17,20,25,30,35,40,45,50],
    "Spending":[39,81,6,77,40,76,6,94,3,72]
}

df = pd.DataFrame(data)

print("Dataset:")
print(df)
X = df[["Income","Spending"]]
kmeans = KMeans(n_clusters=3)
df["Cluster"] = kmeans.fit_predict(X)
print("\nClustered Data:")
print(df)
plt.scatter(df["Income"], df["Spending"], c=df["Cluster"])
plt.xlabel("Income")
plt.ylabel("Spending Score")
plt.title("Customer Segmentation")
plt.show()

