# -*- coding: utf-8 -*-
"""24th Feb TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDl0BI5vaIdz3ZrnVoMdq3YYXMW4VhbN
"""

import pandas as pd
data = {
    "Name": ["Maryum", "Aleena", "Kaamyar", "Ayra", "Ayan"],
    "Marks": [78, 85, 92, 60, None],
    "Attendance": [90, 85, 95, 70, 88],
    "Age": [20, 21, 20, 22, 21]
}
df = pd.DataFrame(data)
df.head()
df.max(numeric_only=True)
df.isnull().sum()

# Five Insights from the Above Analysis
#1.The dataset contains basic student information such as marks, attendance, and age.
#2.Kaamyar has the highest marks in the dataset with a score of 92.
#3.Attendance varies among students, with the highest attendance being 95%.
#4.One missing value is present in the Marks column, which highlights the need for data checking.
#5.Understanding the dataset structure helps in identifying important patterns before further analysis

