# -*- coding: utf-8 -*-
"""24th March TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15EHnLZmXppzukHetX6iIhI54Lt8uTaPF
"""

from sklearn.feature_extraction.text import TfidfVectorizer
documents = [
    "Machine learning is used in many applications",
    "Deep learning is a part of artificial intelligence",
    "Artificial intelligence and machine learning are important",
    "Learning new skills improves knowledge",
    "Data science uses machine learning techniques"
]
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)

tfidf = X.toarray()

words = vectorizer.get_feature_names_out()
for i, doc in enumerate(tfidf):
    print(f"\nDocument {i+1} Top Keywords:")


    top_indices = doc.argsort()[-3:]

    for index in top_indices:
        print(words[index])

#In this task, I learned how to identify important words from a group of documents using TF-IDF.
#The idea is that words which appear more frequently in a particular document, but not in all documents,
#are considered more important.I applied TF-IDF on five sample documents and extracted the top keywords for each one.
#These keywords help in understanding what each document is mainly about.
#I also removed common words like “is”, “and”, and “the” so that only meaningful words are considered.
#Through this, I understood how text data can be cleaned and analyzed to find useful information,
#which is helpful in many real-world applications like search engines and text analysis.