# -*- coding: utf-8 -*-
"""26 Feb TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbi8jxfVflrTpCaPFqWEuFo-yP5NX72j
"""

import pandas as pd
data = {
    "Name": ["Alice", "Bob", "alice", "John"],
    "Age": [25, None, 25, 30],
    "City": ["Delhi", "Mumbai", "delhi", "Bangalore"],
    "Salary": [50000, 60000, 50000, None]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df=df.drop_duplicates()
df["Name"]=df["Name"].str.lower()
df["City"]=df["City"].str.lower()
print("\n Cleaned dataset")
print(df)

