# -*- coding: utf-8 -*-
"""26th March TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VDop8wYuDmTH9mx1RNfNVdPi0RXRZKv
"""

from textblob import TextBlob
reviews = [
    "This movie was amazing and very interesting",
    "I did not like this movie at all",
    "The story was good but a bit slow",
    "Worst movie I have ever seen",
    "It was a fantastic experience"
]
for review in reviews:
    analysis = TextBlob(review)

    print("\nReview:", review)

    if analysis.sentiment.polarity > 0:
        print("Sentiment: Positive")
    elif analysis.sentiment.polarity < 0:
        print("Sentiment: Negative")
    else:
        print("Sentiment: Neutral")

