# -*- coding: utf-8 -*-
"""3rd March TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vs9asgWGfgQrneAWHg2SycqEzbWQQNZ9
"""

import pandas as pd
from sklearn.linear_model import LinearRegression

data = {
    "Study_hours":[1,2,4,5,7,3,6,8],
    "Marks":[30,35,50,55,65,75,85,90]
}

df = pd.DataFrame(data)
print(df)

X = df[["Study_hours"]]
y = df["Marks"]

model = LinearRegression()
model.fit(X, y)

new_data = pd.DataFrame([[6]], columns=["Study_hours"])
prediction = model.predict(new_data)

print("Predicted Marks:", prediction[0])

