# -*- coding: utf-8 -*-
"""9th March TASK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CKL3FkAOu_OKmNiG3od4rL6-SwsnF8or
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
data = {
    "size_sqft":[800,1000,1200,1500,1800,2000],
    "bedrooms":[2,3,3,4,4,5],
    "age":[20,15,10,8,5,3],
    "price":[150000,200000,250000,300000,350000,400000]
}
df = pd.DataFrame(data)
print(df)
X = df[["size_sqft","bedrooms","age"]]
y = df["price"]
model = LinearRegression()
model.fit(X,y)
new_house = pd.DataFrame([[1400,3,12]],
columns=["size_sqft","bedrooms","age"])
prediction = model.predict(new_house)
print("Predicted House Price:", prediction[0])

